CREATE TABLE GRID(
ID NUMBER PRIMARY KEY NOT NULL,
ITEM NVARCHAR2(50) NOT NULL,
PADRE NUMBER NULL,
ACCESO NUMBER NOT NULL,
RUTA NVARCHAR2(50) NULL
);

CREATE SEQUENCE SEC_GRID
START WITH 1368
INCREMENT BY 1;

CREATE TRIGGER TRIGGER_GRID
BEFORE INSERT
ON GRID
FOR EACH ROW 
BEGIN
    SELECT SEC_GRID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Registro de Asuntos', NULL, 1, 'registro-asuntos.html');
COMMIT;

INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Consulta de Asuntos', NULL, 1, 'consulta-asuntos.html');
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Reportes', NULL, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Gatos', 1370, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Reporte de Asuntos', 1370, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Reporte de Juicios', 1370, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Despachos Externos', NULL, 1, 'despachos-externos/busqueda-despachos.html');
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Boletines', NULL, 1, 'boletines/consultas-boletines.html');
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Administracion', NULL, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Catalogos Institucionales', 1376, 1, NULL);
INSERT INTO GRID(ITEM, PADRE, ACCESO, RUTA) VALUES('Bitacora', 1376, 1, NULL);
COMMIT;

SELECT * FROM GRID;