CREATE TABLE DIRECCION_CLIENTE(
ID NUMBER PRIMARY KEY NOT NULL,
CALLE NVARCHAR2(50) NOT NULL,
NUM_INT NUMBER NOT NULL,
NUM_EXT NUMBER NOT NULL,
CP NUMBER NOT NULL
);

CREATE SEQUENCE SEC_DIR
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER TRI_DIR
BEFORE INSERT
ON DIRECCION_CLIENTE
FOR EACH ROW 
BEGIN
    SELECT SEC_DIR.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

INSERT INTO DIRECCION_CLIENTE(CALLE, NUM_INT, NUM_EXT, CP) VALUES('DE LA ROSA', 0, 1, 74135);
INSERT INTO DIRECCION_CLIENTE(CALLE, NUM_INT, NUM_EXT, CP) VALUES('GARDENIAS', 0, 17, 74130);
INSERT INTO DIRECCION_CLIENTE(CALLE, NUM_INT, NUM_EXT, CP) VALUES('ARENAS', 0, 8, 74000);
COMMIT;

SELECT * FROM DIRECCION_CLIENTE;

CREATE TABLE CLIENTE(
ID NUMBER PRIMARY KEY NOT NULL,
NOMBRES NVARCHAR2(30) NOT NULL,
APP NVARCHAR2(20) NOT NULL,
APM NVARCHAR2(20) NOT NULL,
NUM_CEL NUMBER NOT NULL,
CORREO NVARCHAR2(50) NOT NULL,
DIR_ID NUMBER NOT NULL,
STATUS NUMBER NOT NULL,
FOREIGN KEY(DIR_ID) REFERENCES DIRECCION_CLIENTE(ID) ON DELETE CASCADE
);

DROP TABLE CLIENTE;

INSERT INTO CLIENTE VALUES(12, 'JUAN', 'PEREZ', 'SALGADO', 2481596832, 'juan@gmail.com', 1, 1);
INSERT INTO CLIENTE VALUES(15, 'MARIA', 'RAMIREZ', 'LOPEZ', 2225986325, 'mariaRR@gmail.com', 2, 1);
INSERT INTO CLIENTE VALUES(16, 'STEFANY', 'SANCHEZ', 'RAMIREZ', 2225986325, 'fany_sr@gmail.com', 2, 0);
COMMIT;

SELECT * FROM CLIENTE;
